spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # druid相关配置
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://101.43.143.178:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
      username: root
      password: root
      initial-size: 1
      min-idle: 2
      max-active: 5
  servlet:
    # 最大支持文件大小
    # 最大支持请求大小
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #设置实体类的自增主键
  global-config:
    db-config:
      id-type: auto

sql:
  debug: true